kind = "web"
previewPath = "/"
title = "Fiaba"
description = "Une plateforme de social commerce pour permettre aux commerçants de distribuer leurs produits via des vendeurs sociaux, et aux vendeurs de découvrir des campagnes et de suivre leurs revenus au Sénégal."
version = "1.0.0"
id = "artifacts/fiaba"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18441

[services.development]
run = "pnpm --filter @workspace/fiaba run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/fiaba", "run", "build" ]
serve = "static"
publicDir = "artifacts/fiaba/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18441"
BASE_PATH = "/"
